[lief.build]
type             = "Release"
cache            = true
ninja            = true
parallel-jobs    = 0
extra-cmake-opt  = ["-DLIEF_TESTS=on"]
extra-targets    = ["all"]

[lief.formats]
elf     = true
pe      = true
macho   = true
android = true
art     = true
vdex    = true
oat     = true
dex     = true

[lief.features]
json    = true
frozen  = true

[lief.logging]
enabled = true
debug   = false
