[lief.build]
type             = "RelWithDebInfo"
cache            = true
ninja            = true
parallel-jobs    = 0
cxx-compiler     = "clang++"
c-compiler       = "clang"
extra-targets    = ["all"]
extra-cmake-opt  = [
  "-DLIEF_TESTS=on",
  "-DPython_VERSION=3.9",
  "-DCMAKE_COLOR_DIAGNOSTICS=ON",
  "-DCMAKE_CXX_COMPILER=clang++",
  "-DCMAKE_C_COMPILER=clang",
  "-DCMAKE_MODULE_PATH=/cmake/linux/",
]

[lief.formats]
elf     = true
pe      = true
macho   = true
android = true
art     = true
vdex    = true
oat     = true
dex     = true

[lief.features]
json    = true
frozen  = true

[lief.logging]
enabled = true
debug   = false

[lief.cross-compilation]
platform  = "manylinux_2_31_x86_64"
pyversion = "cp39"
abi       = "cp39"
