[lief.build]
type          = "Release"
cache         = true
ninja         = true
strip         = true
parallel-jobs = 0
cxx-compiler  = "clang++"
c-compiler    = "clang"
extra-targets = ["all"]
extra-cmake-opt = [
  "-DPython_VERSION=3.12",
  "-DCMAKE_COLOR_DIAGNOSTICS=ON",
  "-DCMAKE_CXX_COMPILER=clang++",
  "-DCMAKE_C_COMPILER=clang",
  "-DCMAKE_TOOLCHAIN_FILE=/cmake/osx/toolchain.cmake",
  "-DCMAKE_SYSTEM_PROCESSOR=x86_64",
  "-DCMAKE_MODULE_PATH=/cmake/osx/",
]

[lief.formats]
elf     = true
pe      = true
macho   = true
android = true
art     = true
vdex    = true
oat     = true
dex     = true

[lief.features]
json    = true
frozen  = true

[lief.logging]
enabled = true
debug   = false

[lief.cross-compilation]
platform  = "macosx_11_0_x86_64"
pyversion = "cp312"
abi       = "cp312"
