[lief.build]
type          = "Release"
cache         = true
ninja         = true
strip         = true
parallel-jobs = 0
cxx-compiler  = "clang++"
c-compiler    = "clang"
extra-targets = ["all"]
extra-cmake-opt = [
  "-DPython_VERSION=3.11",
  "-DCMAKE_C_COMPILER_LAUNCHER=ccache",
  "-DCMAKE_CXX_COMPILER_LAUNCHER=ccache",
  "-DCMAKE_COLOR_DIAGNOSTICS=ON",
  "-DCMAKE_CXX_COMPILER=clang++",
  "-DCMAKE_C_COMPILER=clang",
  "-DCMAKE_MSVC_RUNTIME=MultiThreaded",
  "-DCMAKE_TOOLCHAIN_FILE=/cmake/windows/toolchain.cmake",
  "-DCMAKE_MODULE_PATH=/cmake/windows/",
]

[lief.formats]
elf     = true
pe      = true
macho   = true
android = true
art     = true
vdex    = true
oat     = true
dex     = true

[lief.features]
json    = true
frozen  = true

[lief.logging]
enabled = true
debug   = false

[lief.cross-compilation]
platform  = "win_amd64"
pyversion = "cp311"
abi       = "cp311"
