[package]
name        = "lief-build"
edition     = "2021"
description = "Build helper for the Rust bindings of LIEF"
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
miette        = { version="5.10", features = [ "fancy" ] }
reqwest       = { version = "0.11.24", features = ["blocking"] }
zip           = "0.6.6"
git-version   = "0.3.9"
semver        = "1.0.22"
