[package]
name        = "lief-ffi"
description = "LIEF ffi"
edition     = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
cxx     = { version = "=1.0.117", features = [ "c++17" ] }
autocxx = { git = "https://github.com/romainthomas/autocxx.git", branch = "0.26.0", version="0.26.0" }

[build-dependencies]
lief-build = { version="1.0.0", path = "../lief-build" }
miette     = { version="=5.10", features = [ "fancy" ] }

[features]
default = ["rustls-tls"]
rustls-tls = ["lief-build/rustls-tls"]
