
name: LIEF Windows x86 Quick

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!release-**'
    tags-ignore:
      - "**"

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [3.9]
    env:
      SCCACHE_CACHE_SIZE: 2G
      SCCACHE_DIR: "C:\\Users\\runner\\AppData\\Local\\Mozilla\\sccache"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x86
    - name: Install system dependencies
      run: |
        choco install ninja
        choco install sccache
        python -m pip install --upgrade pip setuptools
        python -m pip install wheel mako
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: "14.16"
    - name: Get Date
      id: get-date
      run: |
        echo "date=$(/bin/date -u "+%Y-%m-%d-%H;%M;%S")" >> $GITHUB_OUTPUT
      shell: bash
    - name: Save sccache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: "C:\\Users\\runner\\AppData\\Local\\Mozilla\\sccache"
        key: ${{ runner.os }}-x86-sccache-${{ steps.get-date.outputs.date }}
        restore-keys: |
          ${{ runner.os }}-x86-sccache-
    - name: Start sccache server
      run: sccache --start-server
    - name: Set env variables
      run: |
        chcp 65001 #set code page to utf-8
        echo ("LIEF_SAMPLES_DIR=" + $env:RUNNER_TEMP + "/samples") >> $env:GITHUB_ENV
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
      shell: cmd
    - name: â›“ Build Python ${{ matrix.python-version }} & Test
      run: |
        python -m pip install pytest requests
        python tests/dl_samples.py %LIEF_SAMPLES_DIR%
        python -m pip -vv install api/python
        python ./tests/run_pytest.py
      shell: cmd
    - name: ðŸ“Š Print sccache stats
      run: sccache --show-stats
    - name: ðŸ›‘ Stop sccache server
      run: sccache --stop-server || true
